schema-version = 2
release-version = "1.53.0"
project-vendor = "Bottlerocket"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.66.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "4.7.1"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "12.2.0"
vendor = "bottlerocket"
