schema-version = 2
release-version = "1.50.0"
project-vendor = "Bottlerocket"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.65.1"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "4.4.2"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "10.9.0"
vendor = "bottlerocket"
