schema-version = 2
release-version = "1.51.0"
project-vendor = "Bottlerocket"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.65.1"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "4.5.1"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "11.0.1"
vendor = "bottlerocket"
