[licenses]
version = 2

# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93

# Commented license types are allowed but not currently used
allow = [
    "Apache-2.0",
    # "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    # "CC0-1.0",
    "ISC",
    "MIT",
    # "OpenSSL",
    "Unlicense",
    "Zlib",
    "MPL-2.0",
    "Unicode-3.0",
]

exceptions = [
    { name = "unicode-ident", version = "1.0.4", allow = [
        "MIT",
        "Apache-2.0",
        "Unicode-DFS-2016",
    ] },
]

[bans]
# Deny multiple versions or wildcard dependencies.
multiple-versions = "deny"
wildcards = "deny"

deny = [{ name = "structopt" }, { name = "clap" }]

skip = [
    # bottlerocket-settings-sdk requires syn 1.x and 2.x for proc-macros
    # within itself and its dependencies.
    { name = "syn", version = "=1.0" },
]

skip-tree = [
    # windows-sys is not a direct dependency. mio and schannel
    # are using different versions of windows-sys. we skip the
    # dependency tree because windows-sys has many sub-crates
    # that differ in major version.
    { name = "windows-sys" },
]

[sources]
# Deny crates from unknown registries or git repositories.
unknown-registry = "deny"
unknown-git = "deny"

allow-git = [
    # The settings SDK is currently provided as a git dependency,
    # We will allow it as an exception until the following is resolved:
    # https://github.com/bottlerocket-os/bottlerocket-settings-sdk/issues/18
    "https://github.com/bottlerocket-os/bottlerocket-settings-sdk",
]
