# Both containers are disabled by default in off-AWS variants because the user
# must supply user data in order to use the containers.  The admin container
# isn't useful without SSH keys/CA certs, and the control container can only be
# used with hybrid SSM off of AWS.  Users of off-AWS variants might not want to
# use either of those options.
[settings.host-containers.admin]
enabled = false
superpowered = true

[metadata.settings.host-containers.admin.source.setting-generator]
command = "schnauzer-v2 render --template 'public.ecr.aws/bottlerocket/bottlerocket-admin:v0.12.4'"
strength = "weak"

[settings.host-containers.control]
enabled = false
superpowered = false

[metadata.settings.host-containers.control.source.setting-generator]
command = "schnauzer-v2 render --template 'public.ecr.aws/bottlerocket/bottlerocket-control:v0.8.10'"
strength = "weak"
