[package]
name = "docker-compose"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/docker/compose/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/docker/compose/archive/v2.40.3/compose-2.40.3.tar.gz"
sha512 = "aea731cae9e230b5bdf9ad576cf6b04e6edf3233ca8e309b16dbf5a2469aa80ed3082790750d84a6dae981d581e6148e7fba49ddf8d30d7b3c6efcf90576fbe1"
bundle-modules = [ "go" ]
